del *.avi
del *.png
python3 hw3queue.py thegoldenratio4 thegoldenratio4 thegoldenratio4 thegoldenratio4 thegoldenratio4 thegoldenratio4 thegoldenratio4 thegoldenratio4 thegoldenratio4 thegoldenratio4 thegoldenratio4 thegoldenratio4 thegoldenratio4 thegoldenratio4 thegoldenratio4